# Generated by Django 3.1.4 on 2021-01-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='books',
            name='prix',
        ),
        migrations.AddField(
            model_name='books',
            name='nb_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='release_date',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
