# Generated by Django 3.1.4 on 2021-01-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210112_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='nb_pages',
            new_name='nombre_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='release_date',
        ),
        migrations.AddField(
            model_name='book',
            name='auteur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date_de_parution',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=None, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='maison_edition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='titre',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
