# Generated by Django 3.1.4 on 2021-01-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210112_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
