# Generated by Django 3.1.4 on 2021-01-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210113_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.RenameField(
            model_name='livre',
            old_name='maison_edition',
            new_name='maison_édition',
        ),
    ]
