# Generated by Django 3.1.4 on 2021-01-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
