# Generated by Django 3.1.4 on 2021-01-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0002_delete_loans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('emprunté', 'emprunté'), ('non rendu', 'non rendu'), ('rendu', 'rendu')], max_length=50, null=True)),
                ('date_debut_emprunt', models.DateField(max_length=10, null=True)),
                ('date_fin_emprunt', models.DateField(max_length=10, null=True)),
            ],
        ),
    ]
