# Generated by Django 3.1.4 on 2021-01-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210113_0854'),
        ('clients', '0004_auto_20210113_0854'),
        ('loans', '0004_auto_20210112_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.livre'),
        ),
    ]
